---
title: "Analysis of the success of projects launched on the Kickstarter platform"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: united
---


```{r setup, include=FALSE}
#“default”, “cerulean”, “journal”, “flatly”, “darkly”, “readable”, “spacelab”, “united”, “cosmo”, “lumen”, “paper”, “sandstone”, “simplex”, “yeti”

library(kableExtra)
library(coin)
library(flexdashboard)
library(R3PO)
library(RColorBrewer)
library(ggthemes)
library(lubridate)
library(stringr)
library(skimr)
library(dplyr) 
library(readr)
library(ggplot2)
library(magrittr)
library(rpart)
library(rpart.plot)
kickstarter = read_csv("~/shared/minor2_2020/1-Intro/hw2/kickstarter.csv")
usd_goal = read_csv("~/shared/minor2_2020/1-Intro/hw2/usd_goals.csv")


# загрузка данных, предобработка
kickstarter=left_join(kickstarter, usd_goal, by="id")
kickstarter=kickstarter%>%mutate_if(is.character, as.factor)
kickstarter$deadline=as.Date(kickstarter$deadline)
kickstarter$launched=as.Date(kickstarter$launched)
kickstarter$period=difftime(kickstarter$deadline,kickstarter$launched, units = c("days"))
kickstarter$period=round(kickstarter$period, digits=0)
kickstarter$usd_goal_real=round(kickstarter$usd_goal_real, digits=0)
kickstarter = subset(kickstarter, select = -c(goal.x, goal.y,name, currency))

q1=unname(round(quantile(kickstarter$usd_goal_real,probs = (0.00))))
q2=unname(round(quantile(kickstarter$usd_goal_real,probs = (0.95))))
data_short=kickstarter%>%filter(usd_goal_real>q1 & usd_goal_real<q2) 
```


Row {data-weight=100}
-----------------------------------------------------------------------

### Minimum number of backers required for success

```{r}
#значение 7 взято из построенного дерева условий в репорте, определено логически, невозможно рассчитать в чанке с помощью кода

valueBox("7", color="#df78a8", icon="fas fa-level-up-alt")

```

### Accuracy for training and test samples

```{r}
cbPalette <- c("#9ecae1", "#4292c6", "#fdd0a2", "#f16913")
set.seed(1234)
kickstarter_train = kickstarter %>% sample_frac(.8)
kickstarter_test= anti_join(kickstarter, kickstarter_train, by = 'id') %>% select(-id)
kickstarter_train = kickstarter_train %>% select(-id)

kickstarter$state = as.factor(kickstarter$state)
set.seed(1234)
tree1 <- rpart(state ~ backers+usd_goal_real+period, method = "class", data = kickstarter_train, control=rpart.control(cp=0.01))
pred = predict(tree1, type="class", data =kickstarter_train )
t = table(pred, kickstarter_train$state)
a = (t[1,1] + t[2,2])/sum(t)


pred_test = predict(tree1, newdata = kickstarter_test, type="class" )
t = table(pred_test, kickstarter_test$state)
b = (t[1,1] + t[2,2])/sum(t)
valueBox(round(a, digits=2), color="#f59296")

```

### P-value in statistical tests

```{r}
options("scipen"=999)
i_b=independence_test(state ~ backers, data = kickstarter)
i_g=independence_test(state ~ usd_goal_real, data = kickstarter)

t_b=t.test(backers~state, data = kickstarter)
t_g=t.test(usd_goal_real~state, data = kickstarter)

valueBox(round(pvalue(i_g),digits=6), color="#f59296")

```

### Maximum goal-size assigned in successful projects


```{r}
max_usd=data_short%>%filter(state=="successful")%>%summarise(max_usd=max(usd_goal_real))
max_usd_value=max_usd$max_usd[1]
valueBox(round(max_usd_value, digits=0), icon="fas fa-level-down-alt", color="#df78a8")

```



Row {data-height=900}
-----------------------------------------------------------------------


### Average number of backers by categories


```{r}
# график или таблица
cbPalette <- c("#4c0e1e", "#de3f63")
average_backers=kickstarter%>% group_by(main_category, state)%>%summarise(average=mean(backers))

ggplot()+
geom_line(data=average_backers, aes(x=main_category, y= average, group=state, color=factor(state)), size = 1)+
ggtitle("") +
xlab("") +
ylab("") +
 
theme_minimal()+
scale_color_manual(name="State", values=cbPalette)+

theme(axis.text.y = element_text(size = 10, color="black")) +
theme(axis.text.x = element_text(size = 10, color="black", angle = 75, hjust = 1))+
theme(axis.title.x = element_text(size = 14, color="black")) +
theme(axis.title.y=element_text(margin=margin(t=15))) +
theme(legend.position = "right")+
theme(legend.title = element_text(size=10))+
theme(plot.title = element_text(hjust = 0.5))


```
`



### Results of prediction by categories


```{r}
options("scipen"=999, digits=2)

pred_test1<- rename(data.frame(pred_test),c('pred'='pred_test'))
gg = rbind(data.frame(pred), data.frame(pred_test1))
ggg=cbind(kickstarter,gg)
ggg=ggg%>%select(main_category, pred)
ggg1=ggg%>%filter(pred=="successful")%>%count(main_category)
ggg2=ggg%>%filter(pred=="failed")%>%count(main_category)
joined=left_join(ggg1,ggg2,by="main_category")
colnames(joined)=c("Category","Success","Failed")
joined=joined%>%mutate(Percent=Success/(Failed+Success))%>%arrange(-Percent)
kbl(joined, table.attr = "style='width:90%;'" ) %>%
kable_classic( full_width=T, position = "center", font_size = 14)%>%
row_spec(5, bold = F, color = "black", background = "#f59296")%>%
row_spec(7:9, bold = F, color = "black", background = "#f59296")%>%
row_spec(11, bold = F, color = "black", background = "#f59296")

```


### Average goal in USD by categories

```{r}
# график
cbPalette <- c("#4c0e1e", "#de3f63")
average_goal=data_short%>% group_by(main_category, state)%>%summarise(average=mean(usd_goal_real))

ggplot()+
geom_line(data=average_goal, aes(x=main_category, y= average, group=state, color=factor(state)), size = 1)+

xlab("") +
ylab("") +
ggtitle("") +
theme_minimal()+
scale_color_manual(name="State", values=cbPalette)+

theme(axis.text.y = element_text(size = 10, color="black")) +
theme(axis.text.x = element_text(size = 10, color="black", angle = 75, hjust = 1))+
theme(axis.title.x = element_text(size = 14, color="black")) +
theme(axis.title.y=element_text(margin=margin(t=15))) +
theme(legend.position = "right")+
theme(legend.title = element_text(size=10))+
theme(plot.title = element_text(hjust = 0.5))
#theme(axis.text.x = element_blank(), axis.ticks.x=element_blank())

```
